export default {
    appTitle: 'Yabalash',
    selectCountry: 'አገር ይምረጡ',
    selectLanguage: 'ቋንቋ ይምረጡ',
    pleaseChooseACountry: 'Please choose a country',
    pleaseChooseALanguage: 'Please choose a language',
    login: 'ግባ',
    log_in: 'ግባ',
    signup: 'ክፈት',
    sign_up: 'ክፈት',
    register: 'ይመዝገቡ',
    passwordRequired: 'የይለፍ ቃል ያስፈልጋል',
    name: 'ስም',
    name2CharsLong: 'ስም ቢያንስ 2 ቁምፊዎች መሆን አለበት',
    firstName2CharsLong: 'የመጀመሪያ ስም ቢያንስ 2 ቁምፊዎች ርዝመት ሊኖረው ይገባል',
    lastName2CharsLong: 'የአያት ስም ቢያንስ 2 ቁምፊዎች ርዝመት ሊኖረው ይገባል',
    firstNameRequired: 'መጠሪያ ስም ያስፈልጋል',
    lastNameRequired: 'የአያት ስም ያስፈልጋል',
    nameRequired: 'ስም ያስፈልጋል',
    countryRequired: 'ሀገር ያስፈልጋል',
    oldPasswordRequired: 'የድሮ ይለፍ ቃል ያስፈልጋል',
    newPasswordRequired: 'አዲስ የይለፍ ቃል ያስፈልጋል',
    confirmNewPasswordRequired: 'የይለፍ ቃል ያረጋግጡ ያስፈልጋል',
    newAndConfirmPasswordNotMatched: 'አዲስ እና ያረጋግጡ የይለፍ ቃል አይዛመዱም',
    passwordsDonotMatch: 'የይለፍ ቃሎች ተመሳሳይ አይደሉም',
    oldPassword: 'የድሮ ይለፍ ቃል',
    newPassword: 'አዲስ የይለፍ ቃል',
    confirmNewPassword: 'የይለፍ ቃል አረጋግጥ',
    continue: 'ቀጥል',
    verify: 'ያረጋግጡ',
    bySigningup: 'በመመዝገብ በእኛ ይስማማሉ',
    termsAndCondition: 'ውሎች እና ሁኔታዎች',
    emailPhoneNumber: 'ኢሜል ወይም የሞባይል ቁጥር',
    emailPhoneNumberWithoutCode: 'ኢሜል ወይም የሞባይል ቁጥር (ያለ ሀገር ኮድ)',
    email: 'ኢሜይል',
    emailAddress: 'የ ኢሜል አድራሻ',
    contactInfo: 'የመገኛ አድራሻ',
    password: 'የይለፍ ቃል',
    retypePassword: 'የይለፍ ቃል አረጋግጥ',
    firstName: 'የመጀመሪያ ስም',
    lastName: 'የአያት ሥም',
    emailPhoneRequired: 'ኢሜል ወይም የሞባይል ቁጥር ቁጥር ያስፈልጋል',
    enterValidEmailPhone: 'እባክዎ ትክክለኛ ኢሜይል ወይም ስልክ ቁጥር ያስገቡ',
    enterValidEmail: 'እባክዎን ትክክለኛ ኢሜል ያስገቡ',
    forgotPassword_loginScreen: 'መክፈቻ ቁልፉን ረሳኽው?',
    newAccount: 'አዲስ መለያ?',
    alreadyHaveAccount: 'መለያ አልዎት?',
    continueUsingFb: 'ፌስቡክ መጠቀምዎን ይቀጥሉ',
    continueUsingGoogle: 'Google ን መጠቀምዎን ይቀጥሉ',
    or: 'ወይም',
    forgotPassword: 'መክፈቻ ቁልፉን ረሳኽው',
    forgotPasswordDescription: 'ከመለያዎ ጋር የተጎዳኘውን ኢሜል ወይም የሞባይል ቁጥር ያስገቡ።',
    mobileNumber: 'የእጅ ስልክ ቁጥር',
    mobileNumerDescription: 'ባለ 10 አኃዝዎን የሞባይል ቁጥር ያስገቡ።',
    enterValidMobileNo: 'እባክዎን ትክክለኛ የሞባይል ቁጥር ያስገቡ ፡፡',
    mobileNoRequired: 'እባክዎ የተንቀሳቃሽ ስልክ ቁጥር ያስገቡ።',
    otpRequired: 'እባክዎ ኦቲፒ ያስገቡ ፡፡',
    mobileVerification: 'የተንቀሳቃሽ ስልክ ማረጋገጫ',
    mobileVerificationDescription: '{0} -ዲጂት OTP ኮድ ያስገቡ ለተንቀሳቃሽ ስልክ ቁጥርዎ አልተላከም',
    didntReceivedOtp: 'ገና OTP አልተቀበሉም?',
    resendOtp: 'OTP እንደገና ይላኩ',
    furniture: 'የቤት ዕቃዎች',
    homeAccessories: 'የቤት መለዋወጫዎች',
    rugsAndCarpets: 'ምንጣፎች እና ምንጣፎች',
    curtaineAndBlinds: 'መጋረጃዎች እና ዕውሮች',
    gardenAndOutdoor: 'የአትክልት ስፍራ እና ከቤት ውጭ',
    lighteningAndFans: 'መብረቅ እና አድናቂዎች',
    toolsAndHomeImprovements: 'መሣሪያዎች እና የቤት ማሻሻያዎች',
    clothsAndAccessories: 'አልባሳት እና መለዋወጫዎች',
    location: 'አካባቢ',
    categories: 'ምድቦች',
    chats: 'ቻቶች',
    myads: 'የእኔ ማስታወቂያዎች',
    ads: 'ማስታወቂያዎች',
    favourites: 'ተወዳጆች',
    to: 'ለ',
    home: 'ቤት',
    chat: 'ውይይት',
    myAds: 'የእኔ ማስታወቂያዎች',
    profile: 'መገለጫ',
    searchHere: 'እዚህ ይፈልጉ ...',
    findFurniturePlaceholder: 'የቤት እቃዎችን ፣ የቤት እቃዎችን ፣ የቤት እቃዎችን እና ሌሎችን ያግኙ ...',
    details: 'ዝርዝሮች',
    brand: 'የምርት ስም',
    description: 'መግለጫ',
    seller: 'ሻጭ',
    yabalasService: 'ያባላስ አገልግሎት ይሰጣል',
    fixingService: 'የጥገና አገልግሎት',
    insuranceService: 'የመድን አገልግሎት',
    movingService: 'አገልግሎት ማንቀሳቀስ',
    calculateEstimate: 'ግምትን አስላ',
    adId: 'የማስታወቂያ መታወቂያ',
    adPostedAt: 'ማስታወቂያ በ ላይ',
    currentLocation: 'የአሁኑ አካባቢ',
    distance: 'ርቀት',
    km: 'ኪ.ሜ.',
    searchCityOrArea: 'ከተማ ወይም አካባቢ ይፈልጉ',
    recent: 'የቅርብ ጊዜ',
    notification: 'ማስታወቂያ',
    whatAreYouOffering: 'ምንድነው የሚያቀርቡት?',
    selectCategory: 'ምድብ ይምረጡ',
    addSomeDetails: 'አንዳንድ ዝርዝሮችን ያክሉ',
    addTitle: 'ርዕስ ያክሉ',
    addTitleHere: 'ርዕስ እዚህ ያክሉ',
    describeWhatYouAreSelling: 'ምን እንደሚሸጡ ይግለጹ?',
    whatYouAreSelling: 'የሚሸጡት',
    uploadProductPictue: 'የምርት ስዕል ይስቀሉ',
    maxPhotoLimit: 'ከፍተኛ {0} ፎቶዎችን መስቀል ይችላሉ',
    chooseImagesFrom: 'ምስሎችን ይምረጡ ከ',
    setItemPrice: 'የንጥል ዋጋ ያዘጋጁ',
    marketPrice: 'የገቢያ ዋጋ',
    giveawayPrice: 'የስጦታ ዋጋ',
    free: 'ፍርይ',
    whatTypeOfPrice: 'ምን ዓይነት ዋጋ ነው?',
    itemPrice: 'የእቃ ዋጋ',
    setYourLocation: 'አካባቢዎን ያዘጋጁ',
    reviewYourPost: 'ልጥፍዎን ይገምግሙ',
    category: 'ምድብ',
    subCategory: 'ንዑስ ምድብ',
    title: 'ርዕስ',
    productImages: 'የምርት ምስሎች',
    price: 'ዋጋ',
    aed: 'ኤኢዲ',
    yourLocation: 'የእርስዎ አካባቢ',
    postNow: 'አሁን ለጥፍ',
    editPost: 'ልጥፍን ያርትዑ',
    congratulations: 'እንኳን ደስ አለዎት',
    postWillGoLiveShortly: 'የእርስዎ ልጥፍ በቅርቡ ይለቀቃል',
    previewPost: 'ቅድመ እይታን ይመልከቱ',
    yourAddWillExpireOn: 'የእርስዎ ጭማሪ ጊዜው ያልፍበታል በ',
    id: 'መታወቂያ',
    settings: 'ቅንጅቶች',
    manageSettings: 'ቅንብሮችዎን ማቀናበር ይችላሉ',
    changePassword: 'የሚስጥር ቁልፍ ይቀይሩ',
    notifications: 'ማስታወቂያዎች',
    privacyPolicy: 'የ ግል የሆነ',
    helpAndSupport: 'እገዛ እና ድጋፍ',
    logout: 'ውጣ',
    somethingWentWrong: 'የሆነ ስህተት ተከስቷል. እባክዎ ቆየት ብለው ይሞክሩ.',
    skip: 'እንደ እንግዳ ይቀጥሉ',
    pleaseLoginFirst: 'እባክዎ መጀመሪያ ወደ {0} ይግቡ',
    seeYourProfile: 'መገለጫዎን ይመልከቱ',
    accessTheChats: 'ውይይቶቹን መድረስ',
    getYourAds: 'ማስታወቂያዎችዎን ያግኙ',
    filters: 'ማጣሪያዎች',
    clearAll: 'ሁሉንም ያፅዱ',
    priceRange: 'የዋጋ ክልል',
    apply: 'ይተግብሩ',
    deactivate: 'አቦዝን',
    delete: '',
    writeYourMessageHere: 'መልእክትዎን እዚህ ይፃፉ ...',
    save: 'አስቀምጥ',
    addDescription: 'መግለጫ ያክሉ',
    next: 'ቀጣይ',
    done: 'ተጠናቅቋል',
    emailRequired: 'ኢሜል ያስፈልጋል',
    phoneRequired: 'የሞባይል ቁጥር ያስፈልጋል',
    more: 'ተጨማሪ',
    loginFirst: 'መጀመሪያ ይግቡ',
    postAnAd: 'ማስታወቂያ ለጥፍ',
    ok: 'እሺ',
    setYourState: 'ግዛት ይምረጡ',
    setYourArea: 'አካባቢን ይምረጡ',
    setYourCity: 'ከተማ ይምረጡ',
    selectState: 'ግዛት ይምረጡ',
    selectCity: 'ከተማ ይምረጡ',
    pleasePickAState: 'እባክዎን ሁኔታ ይምረጡ',
    pleasePickACity: 'እባክዎን አንድ ከተማ ይምረጡ',
    categoriesNotFound: 'ምድቦች አልተገኙም',
    state: 'ግዛት',
    city: 'ከተማ',
    noDataFound: 'ምንም ውሂብ አልተገኘም',
    pleaseEnterThe: 'እባክዎ {0} ን ያስገቡ',
    pleasePickAnOption: 'እባክዎ ለ {0} አንድ አማራጭ ይምረጡ',
    pleaseChooseAtleast: 'እባክዎ ለ {0} ቢያንስ 1 አማራጭን ይምረጡ',
    chooseAtleast1Pic: 'እባክዎ ለ {0} ቢያንስ 1 ስዕል ይምረጡ',
    chooseAtMostPic: 'ለ {1} ከፍተኛውን {0} ስዕሎችን መምረጥ ይችላሉ',
    choosePriceType: 'እባክዎ ለ {0} የዋጋ አይነት ይምረጡ',
    enterValidPrice: 'እባክዎ ለ {0} ትክክለኛ ዋጋ ያስገቡ',
    enterPrice: 'እባክዎ ለ {0} ዋጋ ያስገቡ',
    pickADate: 'እባክዎ ለ {0} ቀን ይምረጡ',
    areYouSureYouWantToLogout: 'እርግጠኛ ነዎት መውጣት ይፈልጋሉ?',
    cancel: 'ይቅር',
    sessionExpired: 'ክፍለ-ጊዜው አብቅቷል! እባክዎ እንደገና ይግቡ',
    writeSomethingHere: 'የሆነ ነገር እዚህ ይፃፉ ...',
    all: 'ሁሉም',
    permissionToUseCamera: 'ካሜራ እና ማከማቻ ለመጠቀም ፈቃድ',
    weNeedYourPermission: 'የማስታወቂያ ምስሎችን ለመስቀል ካሜራዎን እና ማከማቻዎን ለመጠቀም የእርስዎን ፍቃድ እንፈልጋለን።',
    dontHaveAccount: 'መለያ የለዎትም?',
    businessAccount: 'የንግድ መለያ',
    whatAreYouLookingFor: 'እየፈለክ ያለክው ነገር ምንድን ነው?',
    trendingOn: 'በ {0} ላይ በመታየት ላይ',
    getoff: '{0}% ቅናሽ ያግኙ',
    noTrendingPostsAvailable: 'ምንም በመታየት ላይ ያሉ ልጥፎች የሉም',
    featured: 'FEATURED',
    selectTheCategory: 'ለማስታወቂያዎ የሚመለከተውን ምድብ ይምረጡ',
    facebook: 'ፌስቡክ',
    verified: 'ተረጋግ .ል',
    country: 'ሀገር',
    gender: '.ታ',
    dateOfBirth: 'የትውልድ ቀን',
    postalCode: 'ፖስታ / ዚፕ ኮድ',
    careerLevel: 'የሙያ ደረጃ',
    currentPostition: 'የሥራ መደቡ መጠሪያ',
    salaryExpectation: 'ደመወዝ',
    yourCV: 'የእርስዎ ሲቪ',
    enterValidOTP: 'እባክዎ ትክክለኛ OTP ያስገቡ',
    otpVerification: 'የኦቲፒ ማረጋገጫ',
    otpExpiresIn: 'OTP ጊዜው ያልቃል',
    selectGender: 'Enderታ ይምረጡ',
    uploadResume: 'ከቆመበት ቀጥል ስቀል',
    uploadedResumes: 'የተጫኑ ከቆይታ ማስነሳቶች',
    uploadDocument: 'ሰነድ ጫን',
    selectSalaryExpectation: 'የደመወዝ ደመወዝ ይምረጡ',
    youArePostingAdIn: 'በ \'{0}\' ውስጥ ማስታወቂያ እየለጠፉ ነው',
    almostThere: 'ሊደርስ ነው!',
    theExcellenceIn: 'ልቀቱ በዝርዝሮች ውስጥ ነው',
    addYourPhoto: 'ፎቶዎን ያክሉ',
    yourPostIsAlmostOnline: 'የእርስዎ ልጥፍ መስመር ላይ ማለት ይቻላል ነው!',
    youWantToPromote: 'ይህንን ማስታወቂያ ማስተዋወቅ ይፈልጋሉ',
    promoteAdForDays: 'ማስታወቂያዎን ለ {0} ቀናት ያስተዋውቁ',
    guaranteedViews: 'ዋስትና የተሰጠው {0} ዕይታዎች',
    promoteYourAdFree: 'ማስታወቂያዎን በነፃ ያስተዋውቁ',
    results: 'ውጤቶች',
    profileUpdatedSuccessfully: 'መገለጫ በተሳካ ሁኔታ ዘምኗል',
    searchIn: 'በ \'{0}\' ውስጥ ይፈልጉ',
    recentSearches: 'የቅርብ ጊዜ ፍለጋዎች',
    sellerVerified: 'ሻጭ ተረጋግ .ል',
    itemsSoldBySeller: 'በሻጩ የተሸጡ ዕቃዎች',
    adsSoldBySeller: 'ማስታወቂያዎች በ {0}',
    sms: 'ኤስኤምኤስ',
    call: 'ይደውሉ',
    and: 'እና',
    language: 'ቋንቋ',
    changePhoneNumber: 'ስልክ ቁጥር ይለውጡ',
    newMobileNumber: 'አዲስ የተንቀሳቃሽ ስልክ ቁጥር',
    changeEmail: 'የኢሜል አድራሻን ይቀይሩ',
    newEmail: 'አዲስ ኢሜይል አድራሻ',
    enterValidPassword: 'የይለፍ ቃል ከ _ @. / # & + + - ልዩ ፊደሎችን ፣ ቁጥሮችን እና ማንኛውንም ልዩ ቁምፊዎች ብቻ መያዝ ይችላል ፡፡',
    enterValidOldPassword: 'የድሮ የይለፍ ቃል ከ_ @. / # & + + - ልዩ ፊደሎችን ፣ ቁጥሮችን እና ማንኛውንም ልዩ ቁምፊዎች ብቻ መያዝ ይችላል',
    enterValidNewPassword: 'አዲስ የይለፍ ቃል ከ_ @. / # & + + - ልዩ ፊደሎችን ፣ ቁጥሮችን እና ማንኛውንም ልዩ ቁምፊዎች ብቻ ሊይዝ ይችላል',
    passwordMinMaxLength: 'የይለፍ ቃል ቢያንስ 6 እና ከፍተኛ 15 ቁምፊዎችን ሊይዝ ይችላል',
    newPasswordMinMaxLength: 'አዲስ የይለፍ ቃል በትንሹ 6 እና 15 ከፍተኛ ቁምፊዎችን ሊይዝ ይችላል',
    removeResume: 'ከቆመበት ቀጥል ይወገድ?',
    areYouSureYouWantToRemoveResume: 'እርግጠኛ ነዎት ከቆመበት ማስቀጠልን ከመገለጫዎ ላይ ማስወገድ ይፈልጋሉ?',
    remove: 'ያስወግዱ',
    unableToGetLocation: 'የአሁኑን አካባቢ ማግኘት አልቻልንም ፡፡ ማስታወቂያዎችን ለእርስዎ ቅርብ ለማድረግ እባክዎ አካባቢ / ጂፒኤስ ያንቁ ፡፡',
    similarAds: 'ተመሳሳይ ማስታወቂያዎች',
    noSimilarAdsFound: 'ምንም ተመሳሳይ ማስታወቂያዎች አልተገኙም',
    filteredAds: 'የተጣሩ ማስታወቂያዎች',
    camera: 'ካሜራ',
    photoAndLibrary: 'ፎቶ እና ቤተ መጻሕፍት',
    document: 'ሰነድ',
    noChatsYet: 'ገና ምንም ውይይቶች የሉም!',
    noAdsYet: 'ገና ማስታወቂያዎች የሉም!',
    noFavouritesYet: 'እስካሁን ምንም ተወዳጆች የሉም!',
    premium: 'ፕሪሚየም',
    nonPremium: 'ዋና ያልሆነ',
    activate: 'አግብር',
    selectViewType: 'የእይታ ዓይነት ይምረጡ',
    viewInMap: 'በካርታ ውስጥ ይመልከቱ',
    viewInList: 'በዝርዝሩ ውስጥ ይመልከቱ',
    viewInGrid: 'በፍርግርግ ውስጥ ይመልከቱ',
    edit: 'ያርትዑ',
    deleteAd: 'ሲ Hellልን ያጋሩ።',
    contactUs: 'አግኙን',
    comments: 'አስተያየቶች',
    noCommentsYet: 'እስካሁን አስተያየቶች የሉም',
    writeAComment: 'አስተያየት ፃፍ ...',
    minutes: 'ደቂቃዎች',
    goBack: 'ተመለስ',
    areYouSureYouWantToGoBack: 'እርግጠኛ ነዎት መመለስ ይፈልጋሉ? ወደ ኋላ ከተመለሱ የአሁኑ ለውጦችዎ ይጠፋሉ።',
    faq: 'FAQ',
    maxFileSizeLimit: 'የሚፈቀደው ከፍተኛው የፋይል መጠን {0} ሜባ ነው።',
    maxFileSizeLimitAlert: 'የሚፈቀደው ከፍተኛው የፋይል መጠን {0} ሜባ ነው ፣ እባክዎ ሌላ ይምረጡ ፡፡',
    emailUpdatedSuccessfully: 'ኢሜል በተሳካ ሁኔታ ዘምኗል ፡፡ እባክዎን ኢሜልዎን ለማረጋገጥ የኢሜልዎን የገቢ መልእክት ሳጥን ያረጋግጡ ፡፡',
    phoneUpdatedSuccessfully: 'የተንቀሳቃሽ ስልክ ቁጥር በተሳካ ሁኔታ ዘምኗል።',
    promoteNow: 'ማስታወቂያውን አሁን ያስተዋውቁ',
    areYouSureYouWantToDeleteAd: 'እርግጠኛ ነዎት ይህንን ማስታወቂያ መሰረዝ ይፈልጋሉ?',
    adDeletedSuccessfully: 'ማስታወቂያ በተሳካ ሁኔታ ሰርዝ',
    industry: 'ኢንዱስትሪ',
    destination: 'መድረሻ',
    estimatedWeight: 'የተገመተ ክብደት (በኪ.ግ.)',
    estimatedPrice: 'ግምታዊ ዋጋ',
    pleaseEnterDestination: 'እባክዎ መድረሻ ያስገቡ',
    pleaseEnterEstimatedWeight: 'እባክዎ የተገመተውን ክብደት ያስገቡ',
    pleaseEnterValidEstimatedWeight: 'እባክዎ ትክክለኛ የሚገመት ክብደት ያስገቡ',
    sortBy: 'ቅደምተከተሉ የተስተካከለው',
    ascendingPrice: 'ዋጋን ወደ ላይ ማድረስ',
    descendingPrice: 'የማያስደስት ዋጋ',
    connectToFacebook: 'ወደ ፌስቡክ ይገናኙ',
    facebookConnectedSuccessfully: 'ፌስቡክ በተሳካ ሁኔታ ተገናኝቷል',
    emailVerificationLinkSentSuccessfully: 'የማረጋገጫ አገናኝ ወደ ኢሜልዎ ተልኳል። እባክዎን ኢሜልዎን ለማረጋገጥ የኢሜልዎን የገቢ መልእክት ሳጥን ያረጋግጡ ፡፡',
    noFilterParametersFound: 'ምንም የማጣሪያ መለኪያዎች አልተገኙም!',
    selectOptions: 'አማራጮችን ይምረጡ',
    applyFilter: 'ማጣሪያን ይተግብሩ',
    noFilterFound: 'ምንም ማጣሪያዎች አልተገኙም',
    sellerHasntProvidedHisEmail: 'ሻጩ ኢሜሉን አላቀረበም',
    emailServiceNotAvailableNow: 'በዚህ ጊዜ የኢሜል አገልግሎት አይገኝም ፡፡ እባክዎ ቆየት ብለው ይሞክሩ.',
    sellerHasntProvidedHisMobile: 'ሻጩ የሞባይል ቁጥሩን አልሰጠም',
    mobileServiceNotAvailableNow: 'በዚህ ጊዜ የሞባይል አገልግሎት አይገኝም ፡፡ እባክዎ ቆየት ብለው ይሞክሩ.',
    areYouSureYouWantToDeactivateAd: 'እርግጠኛ ነዎት ይህንን ማስታወቂያ ማቦዘን ይፈልጋሉ?',
    yourCountry: 'ሀገርህ',
    enterEmailInProfile: 'ለመቀጠል እባክዎ ኢሜልዎን ወደ መገለጫዎ ያስገቡ እና ለመቀጠል ፡፡',
    verifyEmailFromProfile: 'ለመቀጠል እባክዎ ከመገለጫዎ ኢሜል ያረጋግጡ።',
    enterMobileInProfile: 'ለመቀጠል እባክዎ የተንቀሳቃሽ ስልክ ቁጥርዎን ወደ መገለጫዎ ያስገቡ።',
    verifyMobileFromProfile: 'ለመቀጠል እባክዎ የተንቀሳቃሽ ስልክ ቁጥርዎን ከመገለጫዎ ያረጋግጡ።',
};
