export default {
    appTitle: 'Yabalash',
    selectCountry: 'Select Country',
    selectLanguage: 'Select Language',
    pleaseChooseACountry: 'Please choose a country',
    pleaseChooseALanguage: 'Please choose a language',
    login: 'Login',
    log_in: 'Log in',
    signup: 'Signup',
    sign_up: 'Sign up',
    register: 'Register',
    passwordRequired: 'Password is required',
    name: 'Name',
    name2CharsLong: 'Name should be atleast 2 characters long',
    firstName2CharsLong: 'First Name should be atleast 2 characters long',
    lastName2CharsLong: 'Last Name should be atleast 2 characters long',
    firstNameRequired: 'First Name is required',
    lastNameRequired: 'Last Name is required',
    nameRequired: 'Name is required',
    countryRequired: 'Country is required',
    oldPasswordRequired: 'Old password is required',
    newPasswordRequired: 'New password is required',
    confirmNewPasswordRequired: 'Confirm password is required',
    newAndConfirmPasswordNotMatched: 'New and Confirm password does not match',
    passwordsDonotMatch: 'Passwords don\'t match',
    oldPassword: 'Old password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm password',
    continue: 'Continue',
    verify: 'Verify',
    bySigningup: 'By signing up you agree to our',
    termsAndCondition: 'Terms & Conditions',
    emailPhoneNumber: 'Email or Mobile Number',
    emailPhoneNumberWithoutCode: 'Email or Mobile Number(without country code)',
    email: 'Email',
    emailAddress: 'Email Address',
    contactInfo: 'Contact Information',
    password: 'Password',
    retypePassword: 'Confirm password',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailPhoneRequired: 'Email or Mobile Number number is required',
    enterValidEmailPhone: 'Please enter a valid email or phone number',
    enterValidEmail: 'Please enter a valid email',
    forgotPassword_loginScreen: 'Forgot Password?',
    newAccount: 'New Account?',
    alreadyHaveAccount: 'Already have an account?',
    continueUsingFb: 'Continue using Facebook',
    continueUsingGoogle: 'Continue using Google',
    or: 'or',
    forgotPassword: 'Forgot Password',
    forgotPasswordDescription: 'Enter the Email or Mobile Number associated with your account.',
    mobileNumber: 'Mobile Number',
    mobileNumerDescription: 'Enter your 10 digit Mobile number. ',
    enterValidMobileNo: 'Please enter a valid Mobile number.',
    mobileNoRequired: 'Please enter the Mobile number.',
    otpRequired: 'Please enter the OTP.',
    mobileVerification: 'Mobile Verification',
    mobileVerificationDescription: 'Enter {0}-digit OTP code sent to your mobile no ',
    didntReceivedOtp: 'Didn\'t receive an OTP yet?',
    resendOtp: 'Re-send OTP',
    furniture: 'Furniture',
    homeAccessories: 'Home accessories',
    rugsAndCarpets: 'Rugs and carpets',
    curtaineAndBlinds: 'Curtains and blinds',
    gardenAndOutdoor: 'Garden and outdoor',
    lighteningAndFans: 'Lightning and fans',
    toolsAndHomeImprovements: 'Tools & home improvements',
    clothsAndAccessories: 'Cloths and accessories',
    location: 'Location',
    categories: 'Categories',
    chats: 'Chats',
    myads: 'My Ads',
    ads: 'ADS',
    favourites: 'Favourites',
    to: 'To',
    home: 'Home',
    chat: 'Chat',
    myAds: 'My Adds',
    profile: 'Profile',
    searchHere: 'Search here...',
    findFurniturePlaceholder: 'Find Furniture, Home Find Furniture, Home Accessories and more...',
    details: 'Details',
    brand: 'Brand',
    description: 'Description',
    seller: 'Seller',
    yabalasService: 'Yabalash Provide a Service',
    fixingService: 'Fixing Service',
    insuranceService: 'Insurance service',
    movingService: 'Moving service',
    calculateEstimate: 'Calculate Estimate',
    adId: 'AD ID',
    adPostedAt: 'Ad post at',
    currentLocation: 'Current Location',
    distance: 'Distance',
    km: 'km',
    searchCityOrArea: 'Search city or area',
    recent: 'Recent',
    notification: 'Notification',
    whatAreYouOffering: 'What are you offering?',
    selectCategory: 'Select Category',
    addSomeDetails: 'Add some details',
    addTitle: 'Add title',
    addTitleHere: 'Add title here',
    describeWhatYouAreSelling: 'Describe what you are selling?',
    whatYouAreSelling: 'What you are selling',
    uploadProductPictue: 'Upload product picture',
    maxPhotoLimit: 'You can upload maximum {0} photos',
    chooseImagesFrom: 'Choose images from',
    setItemPrice: 'Set item price',
    marketPrice: 'Market Price',
    giveawayPrice: 'Giveaway Price',
    free: 'Free',
    whatTypeOfPrice: 'What type of price it is?',
    itemPrice: 'Item Price',
    setYourLocation: 'Set your location',
    reviewYourPost: 'Review your post',
    category: 'Category',
    subCategory: 'Sub Category',
    title: 'Title',
    productImages: 'Product Images',
    price: 'Price',
    aed: 'AED',
    yourLocation: 'Your location',
    postNow: 'Post Now',
    editPost: 'EDIT POST',
    congratulations: 'Congratulations',
    postWillGoLiveShortly: 'Your post will go live shortly',
    previewPost: 'Preview Post',
    yourAddWillExpireOn: 'Your add will expire on:',
    id: 'AD ID:',
    settings: 'Settings',
    manageSettings: 'You can manage your settings',
    changePassword: 'Change Password',
    notifications: 'Notifications',
    privacyPolicy: 'Privacy Policy',
    helpAndSupport: 'Help & Support',
    logout: 'Logout',
    somethingWentWrong: 'Something went wrong. Please try again later.',
    skip: 'Continue as a guest',
    pleaseLoginFirst: 'Please login first to {0}',
    seeYourProfile: 'see your profile',
    accessTheChats: 'access the chats',
    getYourAds: 'get your ads',
    filters: 'Filters',
    clearAll: 'Clear All',
    priceRange: 'Price Range',
    apply: 'APPLY',
    deactivate: 'Deactivate',
    delete: 'Delete',
    writeYourMessageHere: 'Write your message here...',
    save: 'Save',
    addDescription: 'Add Description',
    next: 'Next',
    done: 'Done',
    emailRequired: 'Email is required',
    phoneRequired: 'Mobile number is required',
    more: 'More',
    loginFirst: 'Login First',
    postAnAd: 'post an ad',
    ok: 'Ok',
    setYourState: 'Select State',
    setYourArea: 'Select Area',
    setYourCity: 'Select City',
    selectState: 'Select State',
    selectCity: 'Select City',
    pleasePickAState: 'Please pick a state',
    pleasePickACity: 'Please pick a City',
    categoriesNotFound: 'Categories not found',
    state: 'State',
    city: 'City',
    noDataFound: 'No data found',
    pleaseEnterThe: 'Please Enter the {0}',
    pleasePickAnOption: 'Please pick an option for the {0}',
    pleaseChooseAtleast: 'Please choose atleast 1 option for {0}',
    chooseAtleast1Pic: 'Please choose atleast 1 picture for {0}',
    chooseAtMostPic: 'You can choose maximum {0} pictures for {1}',
    choosePriceType: 'Please choose price type for {0}',
    enterValidPrice: 'Please enter a valid price for {0}',
    enterPrice: 'Please enter price for {0}',
    pickADate: 'Please pick a date for {0}',
    areYouSureYouWantToLogout: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    sessionExpired: 'Session Expired! Please login again',
    writeSomethingHere: 'Write something here...',
    all: 'All',
    permissionToUseCamera: 'Permission to use camera and storage',
    weNeedYourPermission: 'We need your permission to use your camera and storage to upload Ad images.',
    dontHaveAccount: 'Don\'t have an account?',
    businessAccount: 'Business Account',
    whatAreYouLookingFor: 'What are you looking for?',
    trendingOn: 'Trending on {0}',
    getoff: 'Get {0}% off',
    noTrendingPostsAvailable: 'No trending posts available',
    featured: 'FEATURED',
    selectTheCategory: 'Select the category relevant to your ad',
    facebook: 'Facebook',
    verified: 'Verified',
    country: 'Country',
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    postalCode: 'Postal/Zip Code',
    careerLevel: 'Career Level',
    currentPostition: 'Career Position',
    salaryExpectation: 'Salary Expectation',
    yourCV: 'Your CV',
    enterValidOTP: 'Please enter a valid OTP',
    otpVerification: 'OTP verification',
    otpExpiresIn: 'OTP Expires in',
    selectGender: 'Select Gender',
    uploadResume: 'Upload Resume',
    uploadedResumes: 'Uploaded Resumes',
    uploadDocument: 'Upload Document',
    selectSalaryExpectation: 'Select Salary Expectation',
    youArePostingAdIn: 'You are posting ad in \'{0}\'',
    almostThere: 'ALMOST THERE!',
    theExcellenceIn: 'The excellence is in the details',
    addYourPhoto: 'Add Your Photo',
    yourPostIsAlmostOnline: 'Your post is almost online!',
    youWantToPromote: 'You want to promote this ad',
    promoteAdForDays: 'Promote your ad for {0} days',
    guaranteedViews: 'Guaranteed {0} views',
    promoteYourAdFree: 'Promote your ad free',
    results: 'Results',
    profileUpdatedSuccessfully: 'Profile updated successfully',
    searchIn: 'Search in \'{0}\'',
    recentSearches: 'Recent Searches',
    sellerVerified: 'Seller Verified',
    itemsSoldBySeller: 'Items sold by seller',
    adsSoldBySeller: 'Ads by {0}',
    sms: 'SMS',
    call: 'Call',
    and: 'and',
    language: 'Language',
    changePhoneNumber: 'Change Phone Number',
    newMobileNumber: 'New Mobile Number',
    changeEmail: 'Change Email Address',
    newEmail: 'New Email Address',
    enterValidPassword: 'Password can only contain alphabets, numbers and any of the special characters from _@./#&+-',
    enterValidOldPassword: 'Old Password can only contain alphabets, numbers and any of the special characters from _@./#&+-',
    enterValidNewPassword: 'New Password can only contain alphabets, numbers and any of the special characters from _@./#&+-',
    passwordMinMaxLength: 'Password can contain minimum 6 and maximum 15 characters',
    newPasswordMinMaxLength: 'New Password can contain minimum 6 and maximum 15 characters',
    removeResume: 'Remove Resume?',
    areYouSureYouWantToRemoveResume: 'Are you sure you want to remove the resume from your profile?',
    remove: 'Remove',
    unableToGetLocation: 'We are unable to get the current location. Please enable the Location/GPS to get the ads near to you.',
    similarAds: 'Similar ads',
    noSimilarAdsFound: 'No similar ads found',
    filteredAds: 'Filtered Ads',
    camera: 'Camera',
    photoAndLibrary: 'Photo & Library',
    document: 'Document',
    noChatsYet: 'No chats yet!',
    noAdsYet: 'No ads yet!',
    noFavouritesYet: 'No favourites yet!',
    premium: 'Premium',
    nonPremium: 'Nonpremium',
    activate: 'Activate',
    selectViewType: 'Select view type',
    viewInMap: 'View in map',
    viewInList: 'View in list',
    viewInGrid: 'View in grid',
    edit: 'Edit',
    deleteAd: 'Delete Ad.',
    contactUs: 'Contact Us',
    comments: 'comments',
    noCommentsYet: 'No comments yet',
    writeAComment: 'Write a comment...',
    minutes: 'Minutes',
    goBack: 'Go Back',
    areYouSureYouWantToGoBack: 'Are you sure you want to go back? Your current changes will be lost if you go back.',
    faq: 'FAQ',
    maxFileSizeLimit: 'The maximum allowed file size is {0} MB.',
    maxFileSizeLimitAlert: 'The maximum allowed file size is {0} MB, please select another one.',
    emailUpdatedSuccessfully: 'Email updated successfully. Please check your email inbox to verify your email.',
    phoneUpdatedSuccessfully: 'Mobile number updated successfully.',
    promoteNow: 'Promote Ad Now',
    areYouSureYouWantToDeleteAd: 'Are you sure you want to delete this advertisement?',
    adDeletedSuccessfully: 'Ad deleted successfully.',
    industry: 'Industry',
    destination: 'Destination',
    estimatedWeight: 'Estimated Weight (In Kg)',
    estimatedPrice: 'Estimated Price',
    pleaseEnterDestination: 'Please enter a destination',
    pleaseEnterEstimatedWeight: 'Please enter estimated weight',
    pleaseEnterValidEstimatedWeight: 'Please enter a valid estimated weight',
    sortBy: 'Sort By',
    ascendingPrice: 'Ascending Price',
    descendingPrice: 'Descending Price',
    connectToFacebook: 'Connect to Facebook',
    facebookConnectedSuccessfully: 'Facebook Connected Successfully',
    emailVerificationLinkSentSuccessfully: 'A verification link is sent to your email. Please check your email inbox to verify your email.',
    noFilterParametersFound: 'No filter paramaters found!',
    selectOptions: 'Select Options',
    applyFilter: 'Apply Filter',
    noFilterFound: 'No filters found',
    sellerHasntProvidedHisEmail: 'The seller has not provided his email',
    emailServiceNotAvailableNow: 'Email service is not available at this moment. Please try again later.',
    sellerHasntProvidedHisMobile: 'The seller has not provided his mobile number',
    mobileServiceNotAvailableNow: 'Mobile service is not available at this moment. Please try again later.',
    areYouSureYouWantToDeactivateAd: 'Are you sure you want to deactivate this advertisement?',
    yourCountry: 'Your Country',
    enterEmailInProfile: 'Please enter your email into your profile to continue.',
    verifyEmailFromProfile: 'Please verify you email from your profile to continue.',
    enterMobileInProfile: 'Please enter your mobile number into your profile to continue.',
    verifyMobileFromProfile: 'Please verify you mobile number from your profile to continue.',
};
